# Site settings
title: viviのring Blog
SEOTitle: Collection | Habbit Blog
header-img: img/Venice-Italy.jpg
email: 1216800297@qq.com
description: "Every failure is leading towards success."
keyword: "Learning, Collection Blog, Habbit, Java, Android, YuanLe Ring"
url: "http://itx-man.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/itx-man/itx-man.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/facebook.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:
zhihu_username:     yuanle-ring
github_username:    itx-man
facebook_username:  Yuanle Ring
jianshu_username:   ef9e299d3ce9
#twitter_username:  YuanLeRing




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: yuanlering

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7c6143496c2ca4f57090                            #生成的clientID
  clientSecret: 60df3dc6c8107e2150502f32cc1cbac5cf32a0dc    #生成的clientSecret
  repo: itx-man.github.io    #仓库名称
  owner: itx-man    #github用户名
  admin: itx-man
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b2753c72fdde159150ac68e38ba30d9b

# Google Analytics
ga_track_id: 'UA-125439496-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Android",
        href: "https://developer.android.com/"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
